# Generated by Django 3.2.7 on 2022-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('name', models.CharField(blank=True, max_length=200)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('contact', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interests', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='options',
            field=models.CharField(blank=True, choices=[('Hackathon', 'Hackathon'), ('Treasure Hunt', 'Treasure Hunt'), ('Coding Debugging', 'Coding Debugging')], default='Hackathon', max_length=100),
        ),
    ]
